project:
  type: book
  output-dir: _site

engine: julia
julia:
  project: "."

book:
  title: "JuliaPackageTemplate.jl"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: star
        href: https://github.com/RallypointOne/JuliaPackageTemplate.jl/stargazers
        text: "Star"
      - icon: github
        href: https://github.com/RallypointOne/JuliaPackageTemplate.jl
  chapters:
    - index.qmd
    - getting-started.qmd
    - part: "Reference"
      chapters:
        - api.qmd
        - changelog.qmd
        - coverage.qmd

format:
  html:
    css: styles.css
    number-sections: false
    theme:
      light: flatly
      dark: darkly
