project:
  type: book
  output-dir: _site

search:
  type: textbox

book:
  title: "JuliaPackageTemplate.jl"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/RallypointOne/JuliaPackageTemplate.jl
  chapters:
    - index.qmd
    - getting-started.qmd
    - part: "Reference"
      chapters:
        - api.qmd
        - changelog.qmd
        - coverage.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
