project:
  type: book
  output-dir: _site

book:
  title: "JuliaPackageTemplate.jl"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "Changelog"
        href: https://github.com/RallypointOne/JuliaPackageTemplate.jl/blob/main/CHANGELOG.md
      - text: "Coverage"
        href: coverage/
      - icon: github
        href: https://github.com/RallypointOne/JuliaPackageTemplate.jl
  chapters:
    - index.qmd
    - getting-started.qmd
    - api.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
