project:
  type: book
  output-dir: _site

engine: julia

book:
  title: "JuliaPkgTemplate.jl"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/joshday/JuliaPkgTemplate
  chapters:
    - index.qmd
    - getting-started.qmd
    - api.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    number-sections: false
